---
- name: Install curl
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Install Netdata
  shell: bash <(curl -Ss https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/kickstart.sh) --dont-wait
  args:
    executable: /bin/bash

- name: Ensure Netdata is running
  service:
    name: netdata
    state: started

